config/routes.rb
Rails.application.routes.draw do
  get 'download/download'

  resources :tags
  resources :books
  get 'search_form' => 'books#search_form'
  post 'search' => 'books#search'
  root 'welcome#index'

  get 'books/:id/add_to_library' => 'books#add_to_library', as: :add_to_library
  get 'convertions/:id/download' => 'convertions#download_convertion', as: :download_convertion
  get 'convertions' => 'convertions#index', as: :convertions
  delete 'convertions/:id' => 'convertions#destroy', as: :convertion
  get 'books/:id/convert/:output_format' => 'convertions#convert', as: :convert
  get 'books/:id/readepub' => 'books#readepub', as: :read_epub
  get 'books/:id/send_form' => 'books#send_form', as: :send_form
  post 'books/:id/send_book' => 'books#send_book', as: :send_book
  get 'books/:id/download_book' => 'books#download_book', as: :download_book
  get 'books/:id/create_preview' => 'convertions#create_preview', as: :create_preview
  get 'users/ban/:id' => 'users#ban', as: :ban_user
  get 'users/unban/:id' => 'users#unban', as: :unban_user
  get 'users/upgrade/:id' => 'users#upgrade', as: :upgrade_user
  get 'users/downgrade/:id' => 'users#downgrade', as: :downgrade_user
  get 'users/recommendations/:id' => 'users#recommend', as: :recommendate

  get 'books/recommendations/:id' => 'books#recommend', as: :recommendations
  post 'books/rate/:id' => 'books#rate_book', as: :rate_book

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:index, :destroy]
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :uploader, :class_name => 'User'
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :users
  scope :public_books, -> { where(:private => false) }
  validates_presence_of :name
  validates_presence_of :author
  has_attached_file :document#, :styles => { :pdf_thumbnail => ["", :jpg] }, :processors => [:pdf_thumbnail]
  validates_attachment_content_type :document, :content_type => ["application/pdf","application/epub+zip","application/vnd.amazon.ebook","application/x-mobipocket-ebook"], :size => { :in => 0..25.megabytes }
  has_attached_file :thumbnail, styles: { medium: "340x440>", small: "170x220>", thumb: "85x110>" }, default_url: ":style/missing_thumbnail.png"
  validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\Z/  
end

app/controllers/books_controller.rb
require 'will_paginate/array'

class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :add_to_library, :readepub]
  before_action :authenticate_user!, :except => :download_book
  has_scope :public_books, :type => :boolean
  layout false, only: [:readepub]

  def index
    @books = Book.public_books.paginate(page: params[:books_page], per_page: 9)
    @my_books = current_user.books.paginate(page: params[:my_books_page], per_page: 9)
  end

  def show
    @formato = File.extname(@book.document.path).gsub('.','')
    @supported_files = ['epub', 'mobi', 'azw3', 'pdf']
    @supported_files.delete(File.extname(@book.document.path).gsub('.',''))
    if @formato == "pdf"
      @reader = PDF::Reader.new(open(@book.document.path))
    end
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "in6d6hAzrZR7kHndmbEJlYDj0"
      config.consumer_secret     = "qGu2j1olTgUFj1SOIbeLC8ir6WKQlpFagUiuJHI9nx1k9poAb5"
      config.access_token        = "4120758544-yXuOQj3MoMajzGJBA7MURJYK5batw6pcu6TyqwV"
      config.access_token_secret = "RntyIjCItABYGiBalTBRlLtqnnNGOgFWYvtAre69oLF6H"
    end
    @tweets = @client.search("\"#{@book.name}\"", result_type: "recent").take(5)

  end

  def new
    @book = Book.new
    @tags = Tag.all
  end

  def readepub
  end

  def edit
    @tags = Tag.all
  end

  def create
    @book = Book.new(book_params)
    @book.uploader = current_user
    if params[:tags]
      @tags = Tag.find(params[:tags])
      @book.tags = @tags
    else
      @book.tags = []
    end
    respond_to do |format|
      if @book.save
        if !@book.thumbnail.exists?
          @formato = File.extname(@book.document.path).gsub('.','')
          if @formato == "pdf"
            pdf = Magick::ImageList.new(@book.document.path + "[0]")
            thumb = pdf.scale(340, 440)
            file = Tempfile.new(['processed','.png'])
            thumb.write(file.path)
            @book.thumbnail = file
            @book.save
          end
        end
        current_user.books << @book
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        @tags = Tag.find(params[:tags])
        @book.tags = @tags
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_to_library
    current_user.books << @book
    respond_to do |format|
      format.html { redirect_to @book, notice: 'Book was successfully added to your library.' }
      format.json { render :show, status: :ok, location: @book }
    end
  end


  def rate_book
    @book = Book.find(params[:id])
    if rate_check
      if params[:rating].to_f >=1 && params[:rating].to_f <=5 
        current_user.rate!(@book, params[:rating])
      end
    end
    redirect_to @book
  end

  def rate_check

    if Coletivo::Config.ratings_container.all.select{ |rat|  rat.rateable == @book && rat.person == current_user}.length == 0
      return true
    else
      return false
    end

  end

  def rate_average
    @book = Book.find(params[:id])
    suma = 0
    cantidad = 0 
    Coletivo::Config.ratings_container.all.each do |rating|   
      if rating.rateable == @book 
        suma = suma +rating.weight 
        cantidad = cantidad +1 
      end
    end 
    if cantidad == 0
      return 0
    end
    return suma/cantidad
  end
  helper_method :rate_average

  def recommend
    @book = Book.find(params[:id])
    @words = @book.tags
    @books = Book.all.to_a
    @books.map! do |this_book|
      this_book.define_singleton_method(:jaccard_index) do @jaccard_index;  end

      this_book.define_singleton_method("jaccard_index=") do |index|
        @jaccard_index = index || 0.0
      end

      intersection = (@words & this_book.tags).size
      union = (@words | this_book.tags).size

      this_book.jaccard_index = (intersection.to_f / union.to_f) rescue 0.0
      this_book

    end
    @books.sort_by!{ |book| 1 - book.jaccard_index }
    @books = @books [0..9]
  end

  # def convert
  #   @current_format = File.extname(@book.document.path).gsub('.','')
  #   @response = HTTParty.post('https://api.cloudconvert.com/process',
  #   body: {
  #     apikey: "mcgo6n6wlB_vfGnPwjiuxkytOtV3PIs3A1MmC-DJescayEgxqKYHu4_HWAfsCqmKssG4hdOO8K4AZnSM51oz8A",
  #     inputformat: @current_format,
  #     outputformat: @output_format}.to_json,
  #   :headers => {
  #       'Content-Type' => 'application/json',
  #       'Accept' => 'application/json'
  #   })
  #   @upload = HTTParty.post(@response['url'],
  #   body: {
  #   input: "upload",
  #   outputformat: @output_format,
  #   save: true}.to_json,
  #   :headers => {
  #       'Content-Type' => 'application/json',
  #       'Accept' => 'application/json'
  #   })
  #   HTTMultiParty.put(@upload['upload']['url'] + '/' + File.basename(@book.document.path), :query => {
  #     'file' =>  File.new(@book.document.path)})
  #   @conversion = Convertion.new(user_id: current_user.id, convertion_url: @response['url'], name: @book.name)
  #   @conversion.save
  #   redirect_to @book, notice: 'Book added to your conversions'
  # end

  def convert
    @current_format = File.extname(@book.document.path).gsub('.','')
    @response = HTTParty.post('https://api.cloudconvert.com/process',
    body: {
      apikey: "mcgo6n6wlB_vfGnPwjiuxkytOtV3PIs3A1MmC-DJescayEgxqKYHu4_HWAfsCqmKssG4hdOO8K4AZnSM51oz8A",
      inputformat: @current_format,
      outputformat: @output_format}.to_json,
    :headers => {
        'Content-Type' => 'application/json',
        'Accept' => 'application/json'
    })
    @upload = HTTParty.post(@response['url'],
    body: {
    input: "download",
    file: @book.document.path,
    outputformat: @output_format,
    save: true}.to_json,
    :headers => {
        'Content-Type' => 'application/json',
        'Accept' => 'application/json'
    })
    @conversion = Convertion.new(user_id: current_user.id, convertion_url: @response['url'], name: @book.name)
    @conversion.save
    redirect_to @book, notice: 'Book added to your conversions'
  end


  # Initial form for searching (we add this so we can make the tag grid).
  def search_form
    @tags = Tag.all
  end

  # Books searching.
  def search
    @searched_books = Book.public_books
    if search_params[:name].blank? == false
      @searched_books = @searched_books.where("name like ?", '%' + search_params[:name] + '%')
    end
    if search_params[:author].blank? == false
      @searched_books = @searched_books.where("author like ?", '%' + search_params[:author] + '%')
    end
    if params[:tags]
      @tags = Tag.find(params[:tags])
      @tags.each do |t|
        @searched_books = @searched_books.select { |book| book.tags.include? t}
      end
    end
    @searched_books = @searched_books.paginate(page: params[:search_books_page], per_page: 9)
  end

  def send_form
    @book = Book.find(params[:id])
  end

  def send_book
    @book = Book.find(params[:id])
    size = @book.document.size
    email = params[:email]
    message = params[:message]
    if size < 25000000
      BookMailer.send_small_book(email,current_user,@book,message).deliver_now
    else
      BookMailer.send_big_book(email,current_user,@book,message).deliver_now
    end
    redirect_to @book, notice: 'Book sent successfully'
  end

  def download_book
    @book = Book.find(params[:id])
    @formato = File.extname(@book.document.path).gsub('.','')
    book_name = @book.name.gsub(' ','-').downcase + '.' + @formato
    if @formato == "pdf"
      send_file @book.document.path, :type => 'application/pdf', :filename => book_name
    elsif @formato == "epub"
      send_file @book.document.path, :type => 'application/epub+zip', :filename => book_name
    else
      send_file @book.document.path, :type => 'application/vnd.amazon.ebook', :filename => book_name
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :popularity, :private, :document, :thumbnail)
    end

    def search_params
      params.require(:book).permit(:name, :author)
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<div class="clearfix"></div>
<h1 class="text-center">Books</h1>
<div id="tabs" class="c-tabs no-js">
  <div class="c-tabs-nav">
    <a href="#" class="c-tabs-nav__link is-active">Public eBooks</a>
    <a href="#" class="c-tabs-nav__link">My Books</a>
  </div>
  <div class="c-tab is-active">
    <div class="c-tab__content">
      <% @books.each do |book| %>
      <div class="book col-lg-4 col-md-6 col-xs-6 ">
        <p class="text-center book-index-name">
          <%= link_to book.name, book, class: "book-link" %>
          <% if (!current_user.books.include?(book)) %>
          <%= link_to (fa_icon "plus", text: ""), add_to_library_path(book), title: 'Add to Library', rel: 'tooltip' %>
          <% end %>
          <% if(current_user.admin?) %>
          <%= link_to (fa_icon "pencil", text: ""), edit_book_path(book), title: 'Edit', rel: 'tooltip' %>
          <%= link_to (fa_icon "times", text: ""), book, method: :delete,
              data: { confirm: 'Are you sure?' }, title: 'Delete', rel: 'tooltip' %>
          <% end %>
        </p>
        <div class="clearfix"></div>
        <p class="center">
          <%= link_to image_tag(book.thumbnail.url(:small),
              class: "book-thumbnail"), book %>
        </p>
      </div>
      <% end %>
      <div class="clearfix"></div>
      <div class="will_paginate text-center">
        <%= will_paginate @books, :param_name => 'books_page', renderer: BootstrapPagination::Rails, class: "pagination pagination-centered" %>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="c-tab">
    <div class="c-tab__content">
      <% @my_books.each do |book| %>
      <div class="book col-lg-4 col-md-5 col-xs-6 ">
        <p class="text-center book-index-name">
          <%= link_to book.name, book, class: "book-link" %>
          <% if(current_user.admin? || (book.uploader == current_user && book.private)) %>
          <%= link_to (fa_icon "pencil", text: ""), edit_book_path(book), title: 'Edit', rel: 'tooltip' %>
          <%= link_to (fa_icon "times", text: ""), book, method: :delete,
              data: { confirm: 'Are you sure?' }, title: 'Delete', rel: 'tooltip' %>
          <% end %>
        </p>
        <p class="center">
          <%= link_to image_tag(book.thumbnail.url(:small),
              class: "book-thumbnail"), book %>
        </p>
      </div>
      <% end %>
      <div class="will_paginate">
        <%= will_paginate @my_books, :param_name => 'my_books_page' %>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

<script>
  (function() {

  'use strict';

  /**
  * tabs
  *
  * @description The Tabs component.
  * @param {Object} options The options hash
  */
  var tabs = function(options) {
  var el = document.querySelector(options.el);
  var tabNavigationLinks = el.querySelectorAll(options.tabNavigationLinks);
  var tabContentContainers = el.querySelectorAll(options.tabContentContainers);
  var activeIndex = 0;
  var initCalled = false;

  /**
  * init
  *
  * @description Initializes the component by removing the no-js class from
  *   the component, and attaching event listeners to each of the nav items.
  *   Returns nothing.
  */
  var init = function() {
  if (!initCalled) {
  initCalled = true;
  el.classList.remove('no-js');

  for (var i = 0; i < tabNavigationLinks.length; i++)
                      {
                      var link = tabNavigationLinks[i];
                      handleClick(link, i);
                      }
                      }
                      };
                      ;
                      /**
                      * handleClick
                      *
                      * @description Handles click event listeners on each of the links in the
                      *   tab navigation. Returns nothing.
                      * @param {HTMLElement} link The link to listen for events on
                      * @param {Number} index The index of that link
                      */
                      var handleClick = function(link, index) {
                      link.addEventListener('click', function(e) {
                      e.preventDefault();
                      goToTab(index);
                      });
                      };

                      /**
                      * goToTab
                      *
                      * @description Goes to a specific tab based on index. Returns nothing.
                      * @param {Number} index The index of the tab to go to
                      */
                      var goToTab = function(index) {
                      if (index !== activeIndex && index >= 0 && index <= tabNavigationLinks.length) {
                                                                          tabNavigationLinks[activeIndex].classList.remove('is-active');
                                                                          tabNavigationLinks[index].classList.add('is-active');
                                                                          tabContentContainers[activeIndex].classList.remove('is-active');
                                                                          tabContentContainers[index].classList.add('is-active');
                                                                          activeIndex = index;
                                                                          }
                                                                          };

                                                                          /**
                                                                          * Returns init and goToTab
                                                                          */
                                                                          return {
                                                                          init: init,
                                                                          goToTab: goToTab
                                                                          };

                                                                          };

                                                                          /**
                                                                          * Attach to global namespace
                                                                          */
                                                                          window.tabs = tabs;

                                                                          })();
                                                                          </script>
<script>
  var myTabs = tabs({
  el: '#tabs',
  tabNavigationLinks: '.c-tabs-nav__link',
  tabContentContainers: '.c-tab'
  });
  myTabs.init();
</script>

app/views/books/readepubnormal.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <title><%= content_for?(:title) ? yield(:title) : "App_Name" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "App_Name" %>">

  <%= csrf_meta_tags %>
  <%= yield(:head) %>
  <% content_for(:head) do %>
  <% end %>
</head>
  <style type="text/css">
          body {
          }
          #main {
            position: absolute;
            width: 100%;
            height: 100%;
            /* overflow: hidden; */
          }
          #area {
            width: 80%;
            height: 80%;
            margin: 5% auto;
            max-width: 1250px;
          }
          #area iframe {
            border: none;
          }
          #prev {
            left: 40px;
          }
          #next {
            right: 40px;
          }
          .arrow {
            position: absolute;
            top: 50%;
            margin-top: -32px;
            font-size: 64px;
            color: #E2E2E2;
            font-family: arial, sans-serif;
            font-weight: bold;
            cursor: pointer;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
          }
          .arrow:hover {
            color: #777;
          }
          .arrow:active {
            color: #000;
          }
          #controls {
            position: absolute;
            bottom: 16px;
            left: 50%;
            width: 400px;
            margin-left: -200px;
            text-align: center;
            display: none;
          }
          #controls > input[type=range] {
              width: 400px;
          }
        </style>
<body>


        <script src="jquery.min.js" type="text/javascript"></script>

        <script src="zip.min.js" type="text/javascript"></script>

        <script>
            "use strict";

            document.onreadystatechange = function () {
            if (document.readyState == "complete") {
                //EPUBJS.filePath = "js/libs/";
  
                // fileStorage.filePath = EPUBJS.filePath;
                //<%= @book.document.path.gsub(Rails.root.to_s,"").gsub("/public","") %>

                window.reader = ePubReader("<%= @book.document.path.gsub(Rails.root.to_s,"").gsub("/public","") %>");
              }
            };

        </script>

        <!-- File Storage -->
        <!-- <script src="js/libs/localforage.min.js"></script> -->

        <!-- Full Screen -->
    

        <!-- Render -->
        <script src="epub.min.js" type="text/javascript"></script>

        <!-- Hooks -->
      

        <!-- Reader -->
        <script src="reader.min.js" type="text/javascript"></script>

        <!-- Plugins -->
        <!-- <script src="js/plugins/search.js"></script> -->

        <!-- Highlights -->
        <!-- <script src="js/libs/jquery.highlight.js"></script> -->

      <div id="sidebar">
      
        <div id="tocView" class="view">
        </div>
        <div id="searchView" class="view">
          <ul id="searchResults"></ul>
        </div>
        <div id="bookmarksView" class="view">
          <ul id="bookmarks"></ul>
        </div>

      </div>
      <div id="main">

        <div id="titlebar">
          <div id="metainfo">
            <span id="book-title"></span>
            <span id="title-seperator">&nbsp;&nbsp;–&nbsp;&nbsp;</span>
            <span id="chapter-title"></span>
          </div>

        </div>

        <div id="divider"></div>
        <div id="prev" class="arrow">‹</div>
        <div id="viewer"></div>
        <div id="next" class="arrow">›</div>

        <div id="loader"><img src="img/loader.gif"></div>
      </div>

      <div class="overlay"></div>
      <%= link_to 'Back', book_path(@book) %>
</body>

app/views/books/recommend.html.erb
<div class="search-form">
  <%= link_to (fa_icon "search 4x", text: ""), search_form_path,
      class: "search" %>
</div>
<div class="clearfix"></div>
<h1 class="text-center">Similar to <%= @book.name%></h1>
<div id="tabs" class="c-tabs no-js">
  <div class="c-tabs-nav">
    <a href="#" class="c-tabs-nav__link is-active">Similar to <%= @book.name%></a>
  </div>
  <div class="c-tab is-active">
    <div class="c-tab__content">
      <% @books.each do |book| %>
      <div class="book col-lg-4 col-md-6 col-xs-6 ">
        <p class="text-center book-index-name">
          <%= link_to book.name, book, class: "book-link" %>
          <% if (!current_user.books.include?(book)) %>
          <%= link_to (fa_icon "plus", text: ""), add_to_library_path(book) %>
          <% end %>
          <% if(current_user.admin?) %>
          <%= link_to (fa_icon "pencil", text: ""), edit_book_path(book) %>
          <%= link_to (fa_icon "times", text: ""), book, method: :delete,
              data: { confirm: 'Are you sure?' } %>
          <% end %>
        </p>
        <p class="center">
          <%= link_to image_tag(book.thumbnail.url(:small),
              class: "book-thumbnail"), book %>
        </p>
      </div>
      <% end %>
      
    </div>
  </div>
 

app/views/books/search.html.erb
<div class="col-xs-6">
  <h1 class="text-center">Search results:</h1>
    <% @searched_books.each do |book| %>
    <div class="book col-lg-4 col-md-6 col-xs-6 ">
        <p class="text-center book-index-name"><%= link_to book.name, book %></p>
        <%= link_to image_tag(book.thumbnail.url(:small), class: "book-thumbnail"), book %>
    </div>
    <% end %>
</div>

<div class="col-xs-6">
    <div class="will_paginate">
        <%= will_paginate @searched_books, :param_name => 'search_books_page' %>
    </div>
</div>

<%= link_to 'Back to search', search_form_path %>
<%= link_to 'Back', books_path %>

app/views/books/search_form.html.erb
<div id="search-form" class="form">

<%= form_for(Book.new, url: search_path) do |f| %>

<br/>
<br/>
<br/>

<div class="tag-title">
  <h2> Search your book by name and/or author: </h2>
</div>

<div class="name-book">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
</div>

<div class="author-book">
    <%= f.label :author %><br>
    <%= f.text_field :author, class: "form-control" %>
</div>

<div class="tag-title">
  <h2> Search your book by tags: </h2>
</div>
<div class="tag-grid">
  <ul class="tag-grid-ul">
      <% @tags.each do |t| %>
        <li>
          <div class="form-group">
            <%= check_box_tag "tags[]", t.id %>
            <%= f.label t.name  %>
          </div>
        </li>
      <% end %>
  </ul>
</div>

<div class="actions">
    <%= f.submit "Search", id: 'search_books_button' %>
</div>
<% end %>
</div>

app/views/books/show.html.erb
<div class="clearfix"></div>
<div class="row">
    <h1 class="center book-title">
      <% if @formato == "pdf" %>
        <%= link_to @book.name, pdfjs.full_path(file: @book.document.url), :target => "_blank"  %>
      <% elsif @formato == "epub" %>
        <%= link_to @book.name, read_epub_path(@book) %>
      <% else %>
        <%= @book.name %>
      <% end %>
          <% if (!current_user.books.include?(@book)) %>
          <%= link_to (fa_icon "plus", text: ""), add_to_library_path(@book), title: 'Add to Library', rel: 'tooltip' %>
          <% end %>
          <% if(current_user.admin? || (@book.uploader == current_user && @book.private)) %>
          <%= link_to (fa_icon "pencil", text: ""), edit_book_path(@book), title: 'Edit', rel: 'tooltip' %>
          <%= link_to (fa_icon "times", text: ""), @book, method: :delete,
              data: { confirm: 'Are you sure?' }, title: 'Delete', rel: 'tooltip' %>
          <% end %>
    </h1>
<h1 class="center book-title">
      <% if @formato == "pdf" %>
        <%= link_to @book.author, pdfjs.full_path(file: @book.document.url), :target => "_blank"  %>
      <% elsif @formato == "epub" %>
        <%= link_to @book.author, read_epub_path(@book) %>
      <% else %>
        <%= @book.author %>
        <h3 class="center"><%= link_to '(This book has an unsupported format, click here to convert it)', create_preview_path(@book) %></h3>
      <% end %></h1>
  <div class="col-md-6 center">
    <% if @formato == "pdf"%>
      <%= link_to image_tag(@book.thumbnail(:medium), class: "book-preview"), pdfjs.full_path(file: @book.document.url), :target => "_blank" %>
      <%= @extended_path %>
      <%= @path %>
    <% elsif @formato == "epub"%>
      <%= link_to image_tag(@book.thumbnail(:medium), class: "book-preview"), read_epub_path(@book), :target => "_blank" %>
    <% else %>
      <%= image_tag(@book.thumbnail(:medium), class: "book-preview") %>
    <% end %>
<h3> Rate Book</h3>

    <h5> Average Rating: <%= rate_average %> </h5>

    <div>
    <%= form_tag( rate_book_path) do  %>
      <%= text_field_tag "rating"%>
      <%= button_tag(type: "submit", class: "btn btn-default") do %>
          Rate Book
      <% end %>
    <% end %>
    <br>
    <%= link_to "Similar Books", recommendations_path(@book), :class => "btn btn-default" %>
    </div>
  </div>
  <div class="col-md-6 center">
    <% if current_user.admin? %>
    <h3>Uploader</h3>
    <div class="user">
      <%= image_tag @book.uploader.avatar.url(:thumb), class: 'user-thumb' %>
      <%= @book.uploader.name %>
      <% if @book.uploader != current_user %>
      <br>
        <% if @book.uploader.banned? %>
        <%= link_to (fa_icon "plus-circle", text: "Unban"), unban_user_path(@book.uploader), class: 'unban-button' %>
        <% else %>
        <%= link_to (fa_icon "ban", text: "Ban"), ban_user_path(@book.uploader), class: 'ban-button' %>
        <% end %>
      <br>
      <% if @book.uploader.admin? %>
      <%= link_to (fa_icon "arrow-circle-down", text: "Downgrade"), downgrade_user_path(@book.uploader), class: 'downgrade-button' %>
      <% else %>
      <%= link_to (fa_icon "arrow-circle-up", text: "Upgrade"), upgrade_user_path(@book.uploader), class: 'upgrade-button' %>
      <% end %>
      <% end %>
    </div>
    <% end %>
    <h3>Book Tags</h3>
    <% @book.tags.each do |tag| %>
      <%= tag.name %><br/>
    <% end %>
    <% if(current_user.convertions.length < 10) %>
    <h3>Convert to</h3>
    <div class="btn-group">
    <% @supported_files.each do |s| %>
        <%= link_to (s), convert_path(@book, s), :class => "btn btn-default" %>
    <% end %>
    </div>

    <% else %>
    <h3>Remember, there's a limit of 9 active convertions</h3>
    <% end %>
    <h3>Download book</h3>
    <div class="btn-group">
    <%= link_to 'Download', download_book_path(@book), :class => "btn btn-default" %>
    </div>
    <% if @book.private == false or @book.uploader == current_user %>
      <h3>Send to a friend</h3>
      <div class="btn-group">
      <%= link_to 'Send', send_form_path(@book), :class => "btn btn-default" %>
      </div>
    <% end %>
  </div>
  <div class="clearfix"></div>
  <div class="text-center" >
    <h3> Tweets about this book </h3>
    <%@tweets.each do |tweet|%>
      <p><font size="4"><%=tweet.user.screen_name%></font>:  <font size="2"><%=tweet.text%></font> </p>
    <% end %>
  </div>
  <div class="clearfix"></div>
</div>