config/routes.rb
Rails.application.routes.draw do
  get 'download/download'

  resources :tags
  resources :books
  get 'search_form' => 'books#search_form'
  post 'search' => 'books#search'
  root 'welcome#index'

  get 'books/:id/add_to_library' => 'books#add_to_library', as: :add_to_library
  get 'convertions/:id/download' => 'convertions#download_convertion', as: :download_convertion
  get 'convertions' => 'convertions#index', as: :convertions
  delete 'convertions/:id' => 'convertions#destroy', as: :convertion
  get 'books/:id/convert/:output_format' => 'convertions#convert', as: :convert
  get 'books/:id/readepub' => 'books#readepub', as: :read_epub
  get 'books/:id/send_form' => 'books#send_form', as: :send_form
  post 'books/:id/send_book' => 'books#send_book', as: :send_book
  get 'books/:id/download_book' => 'books#download_book', as: :download_book
  get 'books/:id/create_preview' => 'convertions#create_preview', as: :create_preview
  get 'users/ban/:id' => 'users#ban', as: :ban_user
  get 'users/unban/:id' => 'users#unban', as: :unban_user
  get 'users/upgrade/:id' => 'users#upgrade', as: :upgrade_user
  get 'users/downgrade/:id' => 'users#downgrade', as: :downgrade_user
  get 'users/recommendations/:id' => 'users#recommend', as: :recommendate

  get 'books/recommendations/:id' => 'books#recommend', as: :recommendations
  post 'books/rate/:id' => 'books#rate_book', as: :rate_book

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:index, :destroy]
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

end

app/models/convertion.rb
class Convertion < ActiveRecord::Base
  belongs_to :user

  scope :waiting, -> { where(download_link: nil) }
  scope :ready, -> { where.not(download_link: nil) }
end

app/controllers/convertions_controller.rb
class ConvertionsController < ApplicationController
  require "open-uri"
  before_action :authenticate_user!
  before_action :set_output_format, only: [:convert]
  before_action :set_book, only: [:convert, :create_preview]
  before_action :set_convertion, only: [:destroy]

  def index
    @ready = current_user.convertions.ready
    @waiting = current_user.convertions.waiting
  end

  def destroy
    @convertion.destroy
    respond_to do |format|
      format.html { redirect_to convertions_url,
                                notice: 'Convertion was successfully' +
                                ' destroyed.' }
      format.json { head :no_content }
    end
  end

  def convert
    @convertion_url = convert_book(@output_format, @book)
    @convertion = Convertion.new(user_id: current_user.id,
                                 convertion_url: @convertion_url,
                                 name: @book.name)
    @convertion.save
    redirect_to @book, notice: 'Book added to your convertions'
  end

  def create_preview
    @convertion_url = convert_book('epub', @book)
    @response = HTTParty.get(@convertion_url)
    while(@response['step'] == 'finished') do
      sleep 1
      @response = HTTParty.get(@convertion_url)
    end
    @book.document = open('http:' + @response['output']['url'])
    @book.save
  end

  def download_convertion
    @convertion = Convertion.find(params[:id])
    @download_link = @convertion.download_link
    @convertion.destroy
    respond_to do |format|
      format.html { redirect_to @download_link }
      format.json { head :no_content }
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def set_convertion
    @convertion = Convertion.find(params[:id])
  end

  def set_output_format
    @output_format = params[:output_format]
  end

  def get_current_format(book)
    File.extname(book.document.path).gsub('.','')
  end

  def create_process_on_cloud_convert(input_format, output_format)
    HTTParty.post('https://api.cloudconvert.com/process',
                  body: {
                    apikey: "mcgo6n6wlB_vfGnPwjiuxkytOtV3PIs3A1MmC-D"+
                      "JescayEgxqKYHu4_HWAfsCqmKssG4hdOO8K4AZnSM51oz8A",
                    inputformat: input_format,
                    outputformat: output_format}.to_json,
                  :headers => {
                    'Content-Type' => 'application/json',
                    'Accept' => 'application/json'
                  })
  end

  def create_convertion_on_cloud_convert(process, output_format)
    HTTParty.post(process['url'],
                  body: {
                    input: "upload",
                    outputformat: output_format}.to_json,
                  :headers => {
                    'Content-Type' => 'application/json',
                    'Accept' => 'application/json'
                  })
  end

  def upload_book_to_convertion(convertion, book)
    HTTMultiParty.put(convertion['upload']['url'] + '/' + File.basename(
                        book.document.path),
                      :query => {'file' =>  File.new(book.document.path)})
  end

  def convert_book(output_format, book)
    @current_format = get_current_format(book)
    @cloud_convert_process = create_process_on_cloud_convert(
      @current_format, output_format)
    @cloud_convert_convertion = create_convertion_on_cloud_convert(
      @cloud_convert_process, output_format)
    upload_book_to_convertion(@cloud_convert_convertion, book)
    @cloud_convert_process['url']
  end

  def check_convertions
    current_user.convertions.waiting.each do |c|
      @response = HTTParty.get(c.convertion_url)
      if(@response['step'] == 'finished')
        c.download_link = 'http:' + @response['output']['url']
        c.save
      end
    end
  end

end

app/views/convertions/index.html.erb
<div class="clearfix"></div>
<h1 class="text-center">Convertions</h1>
<div id="tabs" class="c-tabs no-js">
  <div class="c-tabs-nav">
    <a href="#" class="c-tabs-nav__link is-active"><%= fa_icon "check", text: "Ready"%></a>
    <a href="#" class="c-tabs-nav__link"><%= fa_icon "refresh", text: "On process"%></a>
  </div>
  <div class="c-tab is-active">
    <div class="c-tab__content">
      <div class="row">
        <% @ready.each do |c| %>
        <div class="ready_book col-lg-4 col-md-6 col-xs-6">
          <h3 class="text-center" ><%= c.name + '  ' %><%= link_to (fa_icon "times", text: ""), c, method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete', rel: 'tooltip' %></h3>
          <%= link_to (fa_icon "download", text: "Download"), download_convertion_path(c), class: "ready_book_link text-center block" %>
        </div>
        <% end %>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="c-tab">
    <div class="c-tab__content">
      <% @waiting.each do |c| %>
      <div class="waiting_book col-lg-4 col-md-6 col-xs-6">
        <h3 class="text-center"><%= c.name %></h3>
      </div>
      <% end %>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
<script>
  $(".ready_book a").click(function(){
  $(this).parent().slideUp();
  $('.notification-label-green').html(parseInt($('.notification-label-green').html(), 10)-1)
  });
</script>
<script>
  (function() {

  'use strict';

  /**
  * tabs
  *
  * @description The Tabs component.
  * @param {Object} options The options hash
  */
  var tabs = function(options) {
  var el = document.querySelector(options.el);
  var tabNavigationLinks = el.querySelectorAll(options.tabNavigationLinks);
  var tabContentContainers = el.querySelectorAll(options.tabContentContainers);
  var activeIndex = 0;
  var initCalled = false;

  /**
  * init
  *
  * @description Initializes the component by removing the no-js class from
  *   the component, and attaching event listeners to each of the nav items.
  *   Returns nothing.
  */
  var init = function() {
  if (!initCalled) {
  initCalled = true;
  el.classList.remove('no-js');

  for (var i = 0; i < tabNavigationLinks.length; i++)
  {
  var link = tabNavigationLinks[i];
  handleClick(link, i);
  }
  }
  };
  ;
  /**
  * handleClick
  *
  * @description Handles click event listeners on each of the links in the
  *   tab navigation. Returns nothing.
  * @param {HTMLElement} link The link to listen for events on
  * @param {Number} index The index of that link
  */
  var handleClick = function(link, index) {
  link.addEventListener('click', function(e) {
  e.preventDefault();
  goToTab(index);
  });
  };

  /**
  * goToTab
  *
  * @description Goes to a specific tab based on index. Returns nothing.
  * @param {Number} index The index of the tab to go to
  */
  var goToTab = function(index) {
  if (index !== activeIndex && index >= 0 && index <= tabNavigationLinks.length) {
  tabNavigationLinks[activeIndex].classList.remove('is-active');
  tabNavigationLinks[index].classList.add('is-active');
  tabContentContainers[activeIndex].classList.remove('is-active');
  tabContentContainers[index].classList.add('is-active');
  activeIndex = index;
  }
  };

  /**
  * Returns init and goToTab
  */
  return {
  init: init,
  goToTab: goToTab
  };

  };

  /**
  * Attach to global namespace
  */
  window.tabs = tabs;

  })();
</script>
<script>
  var myTabs = tabs({
  el: '#tabs',
  tabNavigationLinks: '.c-tabs-nav__link',
  tabContentContainers: '.c-tab'
  });
  myTabs.init();
</script>