config/routes.rb
Rails.application.routes.draw do
  get 'download/download'

  resources :tags
  resources :books
  get 'search_form' => 'books#search_form'
  post 'search' => 'books#search'
  root 'welcome#index'

  get 'books/:id/add_to_library' => 'books#add_to_library', as: :add_to_library
  get 'convertions/:id/download' => 'convertions#download_convertion', as: :download_convertion
  get 'convertions' => 'convertions#index', as: :convertions
  delete 'convertions/:id' => 'convertions#destroy', as: :convertion
  get 'books/:id/convert/:output_format' => 'convertions#convert', as: :convert
  get 'books/:id/readepub' => 'books#readepub', as: :read_epub
  get 'books/:id/send_form' => 'books#send_form', as: :send_form
  post 'books/:id/send_book' => 'books#send_book', as: :send_book
  get 'books/:id/download_book' => 'books#download_book', as: :download_book
  get 'books/:id/create_preview' => 'convertions#create_preview', as: :create_preview
  get 'users/ban/:id' => 'users#ban', as: :ban_user
  get 'users/unban/:id' => 'users#unban', as: :unban_user
  get 'users/upgrade/:id' => 'users#upgrade', as: :upgrade_user
  get 'users/downgrade/:id' => 'users#downgrade', as: :downgrade_user
  get 'users/recommendations/:id' => 'users#recommend', as: :recommendate

  get 'books/recommendations/:id' => 'books#recommend', as: :recommendations
  post 'books/rate/:id' => 'books#rate_book', as: :rate_book

  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:index, :destroy]
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Sakuragi</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.png' %>
</head>

<body>
    <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <% if user_signed_in? %>
                    <li class="sidebar-brand">
                        <div class="user-info-index">
                            <div class="avatar">
                                <%= link_to image_tag(current_user.avatar.url(:small)), edit_user_registration_path %>
                            </div>
                            <h2 class="user-name"><%= link_to current_user.name + ' ' + current_user.last_name, edit_user_registration_path %></h2>
                        </div>
                    </li>
                    <li>
                        <%= link_to (fa_icon "home", text: "Home"), root_path %>
                    </li>
                    <li>
                        <%= link_to (fa_icon "plus", text: "Upload New Book"), new_book_path %>
                    </li>
                    <li>
                        <%= link_to (fa_icon "book", text: "Books"), books_path %>
                    </li>
                    <li>
                        <%= link_to convertions_path do %>
                            <%= fa_icon "exchange", text: "Conversions" %>
                            <% unless (current_user.convertions.ready.empty?) %>
                                <span class="notification-label notification-label-green"><%= current_user.convertions.ready.length %></span>
                            <% end %>
                            <% unless (current_user.convertions.waiting.empty?) %>
                                <span class="notification-label notification-label-yellow"><%= current_user.convertions.waiting.length %></span>
                            <% end %>
                        <% end %>
                    </li>
                    <% if current_user.present? %>
                        <li>
                            <%= link_to (fa_icon "plus-square", text: "Recommendations"), recommendate_path(@current_user) %>
                        </li>
                    <% end %>
                    <% if current_user.admin? %>
                        <li>
                            <%= link_to (fa_icon "users", text: "Users"), users_path %>
                        </li>
                    <% end %>
                    <li>
                        <%= link_to (fa_icon "sign-out", text: "Log Out"), destroy_user_session_path, :method=>'delete' %>
                    </li>
                <% else %>
                    <li>
                        <%= link_to (fa_icon "home", text: "Home"), root_path %>
                    </li>
                    <li>
                        <%= link_to (fa_icon "sign-in", text: "Log In"), new_user_session_path, class: 'login-path' %>
                    </li>
                    <li>
                        <%= link_to (fa_icon "user-plus", text: "Sign In"), new_user_registration_path, class: 'sign-up-path' %>
                        <br/>
                    </li>
                <% end %>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
        <div id="top-bar">
            <div class="top-bar-item">
                <div id="nav-icon1" class="open" data-toggle="tooltip" title="Toggle Sidebar" data-placement="bottom">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
            <% if controller_name == "books" %>
                <div class="top-bar-item">
                    <%= link_to (fa_icon "search 4x", text: ""),
                    search_form_path, class: "search", title: 'Edit', rel: 'tooltip', data: {placement: 'bottom' }  %>
                </div>
            <% end %>
            <div class="clearfix"></div>
        </div>
        <!-- Page Content -->
        <div class="clearfix"></div>
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <% flash.each do |name, msg| %>
                            <%= content_tag :div, msg, :id => "flash_#{name}", :class => "flash" if msg.is_a?(String) %>
                        <% end %>
                        <%= yield %>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#wrapper -->
    </div>
    <script>
     $('#nav-icon1').click(function(e) {
         $(this).toggleClass('open');
         e.preventDefault();
         $("#wrapper").toggleClass("toggled");
     });
     $(document).ready(function() {
         $('#nav-icon1').tooltip();
     });
    </script>
</body>

</html>